version: "3"

services:

  idp-db:
    container_name: idp-db
    image: postgres:15.3-alpine
    restart: unless-stopped
    networks:
      - idp-net
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  idp:
    container_name: idp
    image: keycloak/keycloak:21.0.2
    depends_on:
      - idp-db
    command: start
             --hostname=0.0.0.0
             --hostname-port=8180 
             --http-enabled=true 
             --hostname-strict-https=false 
             --spi-theme-welcome-theme=default 
             --spi-theme-cache-themes=false 
             --spi-theme-cache-templates=false 
             --spi-theme-static-max-age=-1
             --spi-phone-default-service=dummy 
             --spi-phone-default-master-phone-default-region=IR 
             --spi-phone-default-master-number-regex=^09[0-9]{9}$
            #  --spi-phone-default-token-expires-in=60 
            #  --spi-phone-default-source-hour-maximum=10 
            #  --spi-phone-default-target-hour-maximum=3 
            #  --spi-phone-default-master-valid-phone=true 
            #  --spi-phone-default-master-otp-expires=3600 
            #  --optimized if enable : not loading provider plugin
    networks:
      - idp-net
    ports:
      - 8180:8080
    environment:
      KC_DEB: postgres
      KC_DB_URL_HOST: idp-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
    #   # - idp-datastore:/opt/keycloak/data
    #   # - ./store:/opt/keycloak/data
      - ./keycloak-phone-provider/target/providers:/opt/keycloak/providers
      - ./keycloak/themes:/opt/keycloak/themes


volumes:
  idp-datastore:
    name: idp_datastore


networks:
  idp-net:
    name: idp_net
