version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    hostname: mongodb
    restart: on-failure
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin


volumes:
  mongo_data: