version: "3"

services:

  apisix-dashboard:
    container_name: apisix-dashboard
    image: apache/apisix-dashboard:3.0.1-alpine
    restart: always
    volumes:
      - ./logs/apisix-dashboard:/usr/local/apisix-dashboard/logs
      - ./config/gw/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - apisix
      - etcd
    networks:
      - gw-net
    ports:
      - 9000:9000

  apisix:
    container_name: apache-apisix
    # image: apache/apisix:3.3.0-debian
    image: apache/apisix:3.2.1-centos
    restart: always
    volumes:
      - ./logs/apisix:/usr/local/apisix/logs
      - ./config/gw/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      # - ./config/gw/debug.yaml:/usr/local/apisix/conf/debug.yaml:ro
    depends_on:
      - etcd
    networks:
      - gw-net
    ports:
      - "9080:9080/tcp"
      - "9180:9180/tcp" # admin port for v3.0.0
      - "9081:9081/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
    # environment:
    #   - APISIX_STAND_ALONE=true

  etcd:
    container_name: etcd
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - apisix-datastore:/bitnami/etcd
    networks:
      - gw-net
    ports:
      - "2379:2379/tcp"
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"



  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.25.0
    restart: always
    depends_on:
      - apisix
    networks:
      - gw-net
    ports: 
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.7
    restart: always
    depends_on:
      - prometheus
    networks:
      - gw-net
    ports:
      - 3000:3000
    volumes:
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
      - "./config/grafana/dashboards:/var/lib/grafana/dashboards"
      - "./config/grafana/config/grafana.ini:/etc/grafana/grafana.ini"



volumes:
  apisix-datastore:
    name: apisix_datastore
  prometheus-datastore:
    name: prometheus_datastore
  grafana-datastore:
    name: grafana_datastore

networks: 
  gw-net:
    name: gw_net
