version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mysql}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-mysql@123456}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
