version: '3'

services:
  minio:
    image: $BASE_URL_REGISTRY/$SERVICE:$VER
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minio_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - 'minio_data:/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS:-default}

      # # openid config
      # - MINIO_IDENTITY_OPENID_CONFIG_URL=${MINIO_IDENTITY_OPENID_CONFIG_URL}
      # - MINIO_IDENTITY_OPENID_CLIENT_ID=${MINIO_IDENTITY_OPENID_CLIENT_ID}
      # - MINIO_IDENTITY_OPENID_CLIENT_SECRET=${MINIO_IDENTITY_OPENID_CLIENT_SECRET}
      # - MINIO_IDENTITY_OPENID_DISPLAY_NAME=${MINIO_IDENTITY_OPENID_DISPLAY_NAME:-Login with SSO <NAME>}
      # keycloak config
      - MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY=$MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY
      - MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY=$MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY=$MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY=${MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY:-Login with SSO <NAME>}
      - MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY=${MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY:-openid,email,preferred_username}
      - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY=${MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY:-on}

networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local