version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - minio_network
    dns:
      - 1.1.1.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx/
    depends_on:
      - minio


  minio:
    container_name: minio
    image: minio/minio
    command: server /data/minio --address ':9000' --console-address ':9001'
    ports:
      - 9000
      - 9001
    networks:
      - minio_network
    dns:
      - 1.1.1.1
    volumes:
      - minio_data:/data/minio
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL:-http://127.0.0.1/console/}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
   
      # # openid config
      # - MINIO_IDENTITY_OPENID_CONFIG_URL=${MINIO_IDENTITY_OPENID_CONFIG_URL}
      # - MINIO_IDENTITY_OPENID_CLIENT_ID=${MINIO_IDENTITY_OPENID_CLIENT_ID}
      # - MINIO_IDENTITY_OPENID_CLIENT_SECRET=${MINIO_IDENTITY_OPENID_CLIENT_SECRET}
      # - MINIO_IDENTITY_OPENID_DISPLAY_NAME=${MINIO_IDENTITY_OPENID_DISPLAY_NAME:-Login with SSO <NAME>}

      # keycloak config
      # - MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY=$MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY
      # - MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY=$MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY
      # - MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY=$MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY
      # - MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY=${MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY:-Login with SSO <NAME>}
      # - MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY=${MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY:-openid} # openid,email,preferred_username
      # - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY=${MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY:-on}

    deploy:
      restart_policy:
        condition: on-failure
networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local