version: '3'

services:
  minio:
    image: $BASE_URL_REGISTRY/$SERVICE:$VER
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minio_network
    volumes:
      - 'minio_data:/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS:-default}

networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local