up:
	docker compose up
down:
	docker compose down
reup: down up



up_mltiple:
	docker compose -f docker-compose.multiple.yml up

down_multiple:
	docker compose -f docker-compose.multiple.yml down
	
reup_multiple: down_multiple up_mltiple